
interface _GlobalComponents {
      'Btn': typeof import("../components/btn.vue")['default']
    'CardSecondary': typeof import("../components/card-secondary.vue")['default']
    'Card': typeof import("../components/card.vue")['default']
    'Footer': typeof import("../components/footer.vue")['default']
    'HeaderSection': typeof import("../components/header-section.vue")['default']
    'Header': typeof import("../components/header.vue")['default']
    'ImgCard': typeof import("../components/img-card.vue")['default']
    'MustHave': typeof import("../components/must-have.vue")['default']
    'SectionsApps': typeof import("../components/sections/apps.vue")['default']
    'SectionsBanners': typeof import("../components/sections/banners.vue")['default']
    'SectionsBestMobileGame': typeof import("../components/sections/best-mobile-game.vue")['default']
    'SectionsCantStopPlaying': typeof import("../components/sections/cant-stop-playing.vue")['default']
    'SectionsEditorials': typeof import("../components/sections/editorials.vue")['default']
    'SectionsGames': typeof import("../components/sections/games.vue")['default']
    'SectionsTopDownload': typeof import("../components/sections/top-download.vue")['default']
    'SectionsTrending': typeof import("../components/sections/trending.vue")['default']
    'SelectBox': typeof import("../components/select-box.vue")['default']
    'Sidebar': typeof import("../components/sidebar.vue")['default']
    'SocialMedia': typeof import("../components/social-media.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyBtn': typeof import("../components/btn.vue")['default']
    'LazyCardSecondary': typeof import("../components/card-secondary.vue")['default']
    'LazyCard': typeof import("../components/card.vue")['default']
    'LazyFooter': typeof import("../components/footer.vue")['default']
    'LazyHeaderSection': typeof import("../components/header-section.vue")['default']
    'LazyHeader': typeof import("../components/header.vue")['default']
    'LazyImgCard': typeof import("../components/img-card.vue")['default']
    'LazyMustHave': typeof import("../components/must-have.vue")['default']
    'LazySectionsApps': typeof import("../components/sections/apps.vue")['default']
    'LazySectionsBanners': typeof import("../components/sections/banners.vue")['default']
    'LazySectionsBestMobileGame': typeof import("../components/sections/best-mobile-game.vue")['default']
    'LazySectionsCantStopPlaying': typeof import("../components/sections/cant-stop-playing.vue")['default']
    'LazySectionsEditorials': typeof import("../components/sections/editorials.vue")['default']
    'LazySectionsGames': typeof import("../components/sections/games.vue")['default']
    'LazySectionsTopDownload': typeof import("../components/sections/top-download.vue")['default']
    'LazySectionsTrending': typeof import("../components/sections/trending.vue")['default']
    'LazySelectBox': typeof import("../components/select-box.vue")['default']
    'LazySidebar': typeof import("../components/sidebar.vue")['default']
    'LazySocialMedia': typeof import("../components/social-media.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Btn: typeof import("../components/btn.vue")['default']
export const CardSecondary: typeof import("../components/card-secondary.vue")['default']
export const Card: typeof import("../components/card.vue")['default']
export const Footer: typeof import("../components/footer.vue")['default']
export const HeaderSection: typeof import("../components/header-section.vue")['default']
export const Header: typeof import("../components/header.vue")['default']
export const ImgCard: typeof import("../components/img-card.vue")['default']
export const MustHave: typeof import("../components/must-have.vue")['default']
export const SectionsApps: typeof import("../components/sections/apps.vue")['default']
export const SectionsBanners: typeof import("../components/sections/banners.vue")['default']
export const SectionsBestMobileGame: typeof import("../components/sections/best-mobile-game.vue")['default']
export const SectionsCantStopPlaying: typeof import("../components/sections/cant-stop-playing.vue")['default']
export const SectionsEditorials: typeof import("../components/sections/editorials.vue")['default']
export const SectionsGames: typeof import("../components/sections/games.vue")['default']
export const SectionsTopDownload: typeof import("../components/sections/top-download.vue")['default']
export const SectionsTrending: typeof import("../components/sections/trending.vue")['default']
export const SelectBox: typeof import("../components/select-box.vue")['default']
export const Sidebar: typeof import("../components/sidebar.vue")['default']
export const SocialMedia: typeof import("../components/social-media.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyBtn: typeof import("../components/btn.vue")['default']
export const LazyCardSecondary: typeof import("../components/card-secondary.vue")['default']
export const LazyCard: typeof import("../components/card.vue")['default']
export const LazyFooter: typeof import("../components/footer.vue")['default']
export const LazyHeaderSection: typeof import("../components/header-section.vue")['default']
export const LazyHeader: typeof import("../components/header.vue")['default']
export const LazyImgCard: typeof import("../components/img-card.vue")['default']
export const LazyMustHave: typeof import("../components/must-have.vue")['default']
export const LazySectionsApps: typeof import("../components/sections/apps.vue")['default']
export const LazySectionsBanners: typeof import("../components/sections/banners.vue")['default']
export const LazySectionsBestMobileGame: typeof import("../components/sections/best-mobile-game.vue")['default']
export const LazySectionsCantStopPlaying: typeof import("../components/sections/cant-stop-playing.vue")['default']
export const LazySectionsEditorials: typeof import("../components/sections/editorials.vue")['default']
export const LazySectionsGames: typeof import("../components/sections/games.vue")['default']
export const LazySectionsTopDownload: typeof import("../components/sections/top-download.vue")['default']
export const LazySectionsTrending: typeof import("../components/sections/trending.vue")['default']
export const LazySelectBox: typeof import("../components/select-box.vue")['default']
export const LazySidebar: typeof import("../components/sidebar.vue")['default']
export const LazySocialMedia: typeof import("../components/social-media.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
